
figure_path: "figures"

# download_latest_buoy_data
download_buoy_data: True
download_buoy_data_path: "data/buoy"
buoys: 41002, 41049

# download_latest_saildrone_data
download_saildrone_data: True
download_saildrone_data_path: "data/saildrone"
all_saildrones: 1031, 1036, 1040, 1041, 1042, 1045, 1057, 1064, 1065, 1068, 1069, 1083
update_saildrones: 1031, 1036, 1040, 1045, 1057, 1064, 1065, 1068, 1069, 1083

# download_atcf_hurricane_data
download_nhc_atcf_data: True
download_nhc_atcf_data_path: "data/hurricane_forecasts"
atcf_start_year: 2001
atcf_end_year: 2023
preprocess_atcf_wind_radii: True

# download_jason_data
download_jason3_data: False
download_jason3_data_path: "data/satellite/jason3"
jason_number_most_recent_cycles_to_download: 4
jason_predict_overpass_at_location: True
jason_predicted_point_lon: -63.5
jason_predicted_point_lat: 27.5
jason_number_of_future_overpasses: 10


# compare_buoy_saildrone
compare_buoy_saildrone: True
comparison_buoy: 41002
comparison_saildrone: 1057
comparison_start_time: 2023-08-06 00:00:00
comparison_end_time: 2023-08-18 00:00:00
