
figure_path: figures
local_timezone: US/Eastern


# download_latest_buoy_data
download_buoy_data: False
download_buoy_data_path: data/buoy
buoys: 41002, 41043, 41049, 41052, 42099

# download_latest_saildrone_data
download_saildrone_data: True
download_saildrone_data_path: data/saildrone
all_saildrones: 1031, 1036, 1040, 1041, 1042, 1045, 1057, 1064, 1065, 1068, 1069, 1083
update_saildrones: 1031, 1036, 1057, 1064, 1065, 1068, 1069, 1083

# download_jason_data
download_jason3_data: False
download_jason3_data_path: data/satellite/jason3
jason_number_most_recent_cycles_to_download: 4

# predict_jason_altimeter_return_times
jason_predict_overpass_at_location: True
jason_predicted_point_lon: -63.5
jason_predicted_point_lat: 27.5
jason_number_of_future_overpasses: 10

# compare_buoy_saildrone
compare_buoy_saildrone: False
comparison_buoy: 41043
comparison_saildrone: 1064
comparison_start_time: 2023-08-21 12:00:00
comparison_end_time: 2023-08-22 00:00:00
comparison_figure_path: buoy_comparison

# download_atcf_hurricane_data
download_nhc_atcf_data: False
download_nhc_atcf_data_path: data/hurricane_forecasts
atcf_start_year: 2002
atcf_end_year: 2023
preprocess_atcf_wind_radii: False

# download_atcf_current_systems_data
download_nhc_invest_data: True
download_nhc_storm_data: True
download_nhc_btk_data: True
download_nhc_invest_data_path: data/hurricane_forecasts/invest
download_nhc_storm_data_path: data/hurricane_forecasts/storm
download_nhc_btk_data_path: data/hurricane_forecasts/best_track

# plot_nhc_outlook_areas
download_nhc_outlook_data_path: data/hurricane_forecasts/outlooks
outlook_figure_path: nhc_outlook

# create_nhc_outlook_areas_pdf_summary
summary_outlook_figure_path: latest
summary_pdf_path: nhc_outlook_summary
document_author: Ajda Savarin
summary_figure_colorbar: configs/colorbar.png
clean_up_data_and_figures: True

# plot_aircraft_recon
download_aircraft_recon: True
